name: Verify C1 guard

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run :app:verifyC1
        run: ./gradlew :app:verifyC1
